class Verification:
    def GetArmyID() -> int: ...


class GameMap:
    def GetSize() -> {int, int}: ...
    def InMap(x: int, y: int) -> bool: ...
    def IsViewable(x: int, y: int) -> bool: ...

    def GetType(x: int, y: int) -> NODE_TYPE: ...
    def GetUnitNum(x: int, y: int) -> int: ...
    def GetBelong(x: int, y: int) -> int: ...
    def GetKingPos(x: int, y: int) -> {int, int}: ...


class AI_SDK:
    def MoveByDirection(x: int, y: int, moveNum: float,
                        direction: int) -> None: ...

    def MoveByCoordinates(srcX: int,  srcY: int,  destX: int,
                          destY: int,  moveNum: float) -> None: ...

    def IsConnected(srcX: int, srcY: int, destX: int,
                    destY: int) -> bool: ...

    def DirectionToDestination(x: int, y: int, direction: int) -> {
        int, int}: ...
